spring:
  application:
    name: gatling-service
  datasource:
    url: jdbc:postgresql://localhost:5432/gatling
    username: gatling
    password: gatling123
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
            
server:
  port: 8090
