info:
  app:
    name: Sample Customer Service Application
    description: This a demo spring boot application
    version: 1.0.0

spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://localhost:33306/chaos?useSSL=false
    username: chaos
    password: chaos123
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      
server:
  port: 8093
      
chaos:
  monkey:
    enabled: true
    assaults:
      level: 5
      latencyRangeStart: 1000
      latencyRangeEnd: 5000
      latencyActive: false
      exceptionsActive: false
      killApplicationActive: false
    watcher:
      repository: false
      restController: true
      controller: false
      service: false
      component: false
      
management:
  endpoint:
    chaosmonkey:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,chaosmonkey
